# This is a basic workflow to help you get started with Actions

name: SonarScan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sonarQubeTrigger:
      name: SonarQube Trigger
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: SonarQube Scan
        uses: warchant/setup-sonar-scanner@v1
      - name: SC
        run: sonar-scanner
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
             -Dsonar.organization=1corp
             -Dsonar.host.url=https://sonarcloud.io/
             -Dsonar.projectKey=sonar-scanner-action
